Burrows Wheeler
GolrovKirill/SPbU-Prog2 pull request #2
Opened 2024-03-23 00:34 UTC by GolrovKirill

2024-03-23 00:45 UTC, NikitosKey commented
Ля какой

2024-03-31 14:42 UTC, zhitm requested changes
3/4(6)
К публичным методам надо бы доку делать. [Гайд](https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/language-specification/documentation-comments)

2024-03-31 14:42 UTC, zhitm commented on BurrowsWheeler/BurrowsWheeler/Program.cs
> +        string strout = BWT.Decoding((strin));
Как пользователь поймет, что именно ему надо вводить? Хотелось бы какое-то приглашение к вводу и сообщение о том, что ему выводится.

2024-03-31 14:42 UTC, zhitm commented on BurrowsWheeler/BurrowsWheeler/BWT.cs
> +        int[] quantity = new int[255];
1) Тут стоило бы использовать var, не надо дублировать типы.
2) Размер char в C# не 1 байт, а 2 байта. 2^16 > 255 :) А выделять массив размером 2^16 не самая эффективна идея по памяти.

2024-03-31 14:42 UTC, zhitm commented on BurrowsWheeler/BurrowsWheeler/BWT.cs
> +        s = "$" + s;
А если в строке уже есть такой символ?

2024-03-31 14:42 UTC, zhitm commented on BurrowsWheeler/BurrowsWheeler/BWT.cs
> +        return str; //Возвращаем закодировонную строку
"на выходе должна получиться строка, преобразованная Барроузом-Уилером, и позиция конца строки в результате преобразования" :)

2024-04-26 09:51 UTC, zhitm commented
Вывод был подправлен, а остальные моменты пока нет, +1 балл (4)

2024-04-27 10:55 UTC, merged